In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/nikitagupta1812/emojidataset/train (1).txt

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(
    "/kaggle/input/datasets/nikitagupta1812/emojidataset/train (1).txt",
    sep=";",
    header=None,
    names=["text", "emotion"]
)

In [4]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

## STEP-1 LOWERCASE ELEMENTS

In [5]:
df.isnull()

        text  emotion
0      False    False
1      False    False
2      False    False
3      False    False
4      False    False
...      ...      ...
15995  False    False
15996  False    False
15997  False    False
15998  False    False
15999  False    False

[16000 rows x 2 columns]

In [6]:
unique_emotion = df['emotion'].unique()
emotion_numbers = {}
i=0
for emo in unique_emotion:
    emotion_numbers[emo] = i
    i+= 1


df['emotion'] = df['emotion'].map(emotion_numbers)

In [7]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [8]:
df['text'] = df['text'].apply(lambda x: x.lower())

## STEP -2 REMOVING PUNCTUATIONS

In [9]:
import string
def remove_punc(text):
    return text.translate(str.maketrans('','',string.punctuation))

In [10]:
df['text']= df['text'].apply(remove_punc)

In [11]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new+i
            return new
df['text'] = df['text'].apply(remove_punc)

## STEP -3 REMOVING STOPWORDS

In [12]:
## CORPUS- Acollection of texts Like a dataset of Texts 
## SENTENCES - A GROUP PF WORDS THAT FORMS A MEANINGFUL STATEMENT
## TOKEN - EACH INDIVIDUAL WORD OR SYMBOL IN THE TEXT CALLED A TOKEN.
##

In [13]:
import nltk

In [14]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [15]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [16]:
stop_words = set(stopwords.words('english'))
len(stop_words) ## length of stopwords

198

In [17]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [18]:
from nltk.tokenize import word_tokenize

def remove(text):
    words = word_tokenize(text)
    cleaned = []

    for i in words:
        if i not in stop_words:
            cleaned.append(i)

    return  ''.join(cleaned)

In [19]:
df['text'] = df['text'].apply(remove)

In [20]:
df.loc[1]['text']

'gofeelinghopelessdamnedhopefularoundsomeonecaresawake'

from sklearn.feature_extraction.text import CountVectorizer

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
documents = [
    'i love Pizza',
    'Pizza Is Best',
    'i Love Pasta Also'
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)
print("Vocabulary: ", vectorizer.get_feature_names_out())
print("\nBow Matrix:\n ", X.toarray())

Vocabulary:  ['also' 'best' 'is' 'love' 'pasta' 'pizza']

Bow Matrix:
  [[0 0 0 1 0 1]
 [0 1 1 0 0 1]
 [1 0 0 1 1 0]]

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(df['text'],df['emotion'],test_size=0.20,random_state=42)

In [23]:
X_test

8756                                 ivemadeweekfeelbeaten
4660                                feelstrategyworthwhile
6095                          feelworthlessweaksaywantfind
304                                          feelclevernov
8241                           immovedivefeelingkindgloomy
                               ...
15578    feelusefulpulpitfindironicoftenquestionefficac...
5746                   driedbladdersreadydayimfeelingbrave
6395                                feelthrilledmatterdays
7624     wokemorningtextmrcdeclaringwalkingworktypedmil...
15245                                             feeldumb
Name: text, Length: 3200, dtype: object

In [24]:
X_train

676      referscoursethoughcanthelpfeelingsomehowironic...
12113                     imstartingfeelimsufferingfatigue
7077     feellikeprobablywouldlikedbooklittlebitsimples...
13005                                    reallyfeelawkward
12123    imfeelinglittlegrumpytodaylameweatherteasegotw...
                               ...
13418       loveleavereaderfeelingconfusedslightlydeceived
5390                                          feeldelicate
860                             startingfeellittlestressed
15795                  feelstressedtiredwornshapeneglected
7270               feelsomeonerudewronglydonesomethinglose
Name: text, Length: 12800, dtype: object

In [25]:
df.shape

(16000, 2)

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [27]:
bow_vectorizer = CountVectorizer()

In [28]:
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [29]:
from sklearn.naive_bayes import MultinomialNB ## NB -NAIVE BAYES
from sklearn.metrics import accuracy_score

In [30]:
nb_model = MultinomialNB()

In [31]:
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [32]:
pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test,pred_bow))

0.3234375

In [33]:
pred_bow

array([5, 5, 5, ..., 5, 5, 5], shape=(3200,))

In [34]:
y_test

8756     0
4660     5
6095     0
304      5
8241     0
        ..
15578    5
5746     5
6395     5
7624     5
15245    0
Name: emotion, Length: 3200, dtype: int64

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [36]:
tfidf_vectorizer = TfidfVectorizer()

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [37]:
nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [38]:
y_pred = nb2_model.predict(X_test_tfidf)

In [39]:
print(accuracy_score(y_test,y_pred))

0.3234375

In [40]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(max_iter = 1000)

In [41]:
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [42]:
log_pred = logistic_model.predict(X_test_tfidf)

In [43]:
print(accuracy_score(y_test,log_pred))

0.3246875