In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/brendan45774/test-file/tested.csv

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('/kaggle/input/datasets/brendan45774/test-file/tested.csv')[['Age','Pclass','Fare','Survived']]
df

      Age  Pclass      Fare  Survived
0    34.5       3    7.8292         0
1    47.0       3    7.0000         1
2    62.0       2    9.6875         0
3    27.0       3    8.6625         0
4    22.0       3   12.2875         1
..    ...     ...       ...       ...
413   NaN       3    8.0500         0
414  39.0       1  108.9000         1
415  38.5       3    7.2500         0
416   NaN       3    8.0500         0
417   NaN       3   22.3583         0

[418 rows x 4 columns]

In [4]:
df.head()

    Age  Pclass     Fare  Survived
0  34.5       3   7.8292         0
1  47.0       3   7.0000         1
2  62.0       2   9.6875         0
3  27.0       3   8.6625         0
4  22.0       3  12.2875         1

In [5]:
df.isnull().mean()*100

Age         20.574163
Pclass       0.000000
Fare         0.239234
Survived     0.000000
dtype: float64

In [6]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [7]:
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [8]:
X_train.head()

      Age  Pclass     Fare
280  23.0       3   8.6625
284   2.0       3  20.2125
40   39.0       3  13.4167
17   21.0       3   7.2250
362  31.0       2  21.0000

In [9]:
knn = KNNImputer(weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [10]:
pd.DataFrame(X_train,columns=X_train.columns)

      Age  Pclass     Fare
280  23.0       3   8.6625
284   2.0       3  20.2125
40   39.0       3  13.4167
17   21.0       3   7.2250
362  31.0       2  21.0000
..    ...     ...      ...
299  29.0       3   7.8542
22    NaN       1  31.6833
72   29.0       3   7.9250
15   24.0       2  27.7208
168   NaN       1  27.7208

[334 rows x 3 columns]

In [11]:
lr = LogisticRegression()
lr.fit(X_train_trf,y_train)
y_pred = lr.predict(X_test_trf)
accuracy_score(y_test,y_pred)

0.6428571428571429

In [12]:
## Comparision with Simple Imputer--> Mean
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [13]:
lr = LogisticRegression()
lr.fit(X_train_trf2,y_train)
y_pred2 = lr.predict(X_test_trf2)
accuracy_score(y_test,y_pred2)

0.6428571428571429